name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours (adjust if you want a different frequency)
  workflow_dispatch: # Allows you to manually trigger the action from the "Actions" tab

jobs:
  build:
    name: Generate GitHub-Snake
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mahfuzahmedzisan # <--- Make sure this is your username!
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg? palette=github-dark

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # The branch where the SVG will be pushed
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}